language: python
python:
  - "2.7"
before_script:
  - wget https://github.com/samtools/htslib/releases/download/1.3.2/htslib-1.3.2.tar.bz2
  - tar jxvf htslib-1.3.2.tar.bz2 
  - cd htslib-1.3.2 && make && export PATH=$PATH:$PWD && cd ..
  - wget https://github.com/arq5x/bedtools2/releases/download/v2.25.0/bedtools-2.25.0.tar.gz
  - tar zxvf bedtools-2.25.0.tar.gz
  - cd bedtools2 && make && export PATH=$PATH:$PWD/bin && cd ..
  - pip install annot_utils
  - pip install pysam
  - pip install junc_utils
  - pip install intron_retention_utils

script:
  - pip install .
#   - python setup.py test

